import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="image">
                <Image
                    src="https://colombiagasvehicular.s3.amazonaws.com/advertising/Revisi%C3%B3n-Anual-web_Mesa-de-trabajo-1_Mesa-de-trabajo-1.png"
                    alt="Vercel Logo"
                    height="100px"
                    width="100px"
                    layout="responsive"
                />
            </div>

            <style jsx>{`
            
                .image {
                    width: 20rem;
                    margin: auto;
                }
            
            `}</style>
        </div>
    )
}

export default Home
